programme : programme.o main.o
						gcc -o programme programme.o main.o

programme.o : programme.c
						gcc -o programme.o -c programme.c -w -Wall -ansi -pedantic

main.o : 		main.c
						gcc -o main.o -c main.c -w -Wall -ansi -pedantic
