programme : saisie.o trie.o affichage.o main.o
						gcc -o programme saisie.o trie.o affichage.o main.o

saisie.o : saisie.c
						gcc -o saisie.o -c saisie.c -w -Wall -ansi -pedantic

trie.o : 		trie.c
						gcc -o trie.o -c trie.c -w -Wall -ansi -pedantic

affichage.o : 		affichage.c
						gcc -o affichage.o -c affichage.c -w -Wall -ansi -pedantic

main.o : 		main.c
						gcc -o main.o -c main.c -w -Wall -ansi -pedantic
